export class StepFunctionOutputConstants {

    static PARAMETER_VALUES = 'parameterValues';
    static TABLE_INFO = 'tableInfo';
    static DESCRIBE_CONTINUOUS_BACKUPS_OUTPUT = 'describeContinuousBackupsOutput';
    static EXPORT_TIME_PARAMETER_TO_USE_OUTPUT = 'exportTimeParameterToUseOutput';
    static GET_NEXT_INCREMENTAL_EXPORT_TIME_OUTPUT = 'getNextIncrementalExportTimeOutput';
    static PUT_INCREMENTAL_EXPORT_TIME_PARAMETER_OUTPUT = 'putIncrementalExportTimeParameterOutput';
    static PUT_FULL_EXPORT_TIME_PARAMETER_OUTPUT = 'putFullExportTimeParameterOutput';
    static PUT_WORKFLOW_INITIATED_PARAMETER_OUTPUT = 'putWorkflowInitiatedParameterOutput';
    static WORKFLOW_INITIALIZED_PARAMETER_OUTPUT = 'workflowInitializedParameterOutput';
    static INCREMENTAL_EXPORT_PARAMETER_OUTPUT = 'incrementalExportParameterOutput';
    static DESCRIBE_INCREMENTAL_EXPORT_OUTPUT = 'describeIncrementalExportOutput';
    static DESCRIBE_FULL_EXPORT_OUTPUT = 'describeFullExportOutput';
    static NOTIFY_ON_INCREMENTAL_EXPORT_START_TIME_OUTSIDE_PITR_WINDOW_OUTPUT = 'notifyOnIncrementalExportStartTimeOutsidePitrWindowOutput';
    static NOTIFY_ON_PITR_DISABLED_OUTPUT = 'notifyOnPitrDisabledOutput';
    static INCREMENTAL_EXPORT_OUTPUT = 'incrementalExportOutput';
    static NOTIFY_ON_INCREMENTAL_EXPORT_OUTPUT = 'notifyOnIncrementalExportOutput';
    static UPDATE_CONTINUOUS_BACKUP_OUTPUT = 'updateContinuousBackupOutput';
    static FULL_EXPORT_OUTPUT = 'fullExportOutput';
    static NOTIFY_ON_FULL_EXPORT_OUTPUT = 'notifyOnFullExportOutput';
    static NOTIFY_ON_FULL_EXPORT_RUNNING_OUTPUT = 'notifyOnFullExportRunningOutput';
    static NOTIFY_ON_DESCRIBE_TABLE_FAILED_OUTPUT = 'NotifyOnDescribeTableFailedOutput';
    static DELETE_LAST_INCREMENTAL_EXPORT_TIME_PARAMETER_OUTPUT = 'deleteLastIncrementalExportTimeParameterOutput';
    static NOTIFY_ON_PITR_GAP_OUTPUT = 'notifyOnPitrGapOutput';
    static PUT_WORKFLOW_STATE_PARAMETER_TO_PITR_GAP_OUTPUT = 'putWorkflowStateParameterToPitrGapOutput';
    static PUT_WORKFLOW_STATE_PARAMETER_TO_NORMAL_OUTPUT = 'putWorkflowStateParameterToNormalOutput';
    static PUT_WORKFLOW_ACTION_PARAMETER_TO_RUN_OUTPUT = 'putWorkflowActionParameterToRunOutput';
}
